### PR TITLE
[WD-12159] chore: Updated yarn.lock dependencies

### PR DESCRIPTION
**Pull request by Kxiru**
## Done
- Used ncu -u command to update dependencies
- Maintained the correct version of "intl-tel-input":"17.0.21".

## QA
- Check out this feature branch
- Review yarn.lock file

## Issue / Card

Fixes out of date dependencies

## Screenshots

N/A

### CODE REVIEW

**Review by edlerd — CHANGES_REQUESTED** [review]
The demo build is failing because it can't find `esbuild`. I assume some of the dependencies can't be moved to dev dependencies. Can you have a look and ensure the build passes?

**Comment by Kxiru** [comment]
> The demo build is failing because it can't find `esbuild`. I assume some of the dependencies can't be moved to dev dependencies. Can you have a look and ensure the build passes?

Hey David,
How do you know that esbuild cannot be found? When I read the error logs, it implies it cannot find build-css and build-js. Is there another place that I should be looking?

**Comment by edlerd** [comment]
> > The demo build is failing because it can't find `esbuild`. I assume some of the dependencies can't be moved to dev dependencies. Can you have a look and ensure the build passes?
> 
> Hey David, How do you know that esbuild cannot be found? When I read the error logs, it implies it cannot find build-css and build-js. Is there another place that I should be looking?

From the jenkins log:

```
#26 0.520 Error: Cannot find module 'esbuild'
#26 0.520 Require stack:
#26 0.520 - /srv/build.js
#26 0.520     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
#26 0.520     at Module._load (node:internal/modules/cjs/loader:986:27)
#26 0.520     at Module.require (node:internal/modules/cjs/loader:1233:19)
#26 0.520     at require (node:internal/modules/helpers:179:18)
#26 0.520     at Object.<anonymous> (/srv/build.js:1:15)
#26 0.520     at Module._compile (node:internal/modules/cjs/loader:1358:14)
#26 0.520     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
#26 0.520     at Module.load (node:internal/modules/cjs/loader:1208:32)
#26 0.520     at Module._load (node:internal/modules/cjs/loader:1024:12)
#26 0.520     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
#26 0.520   code: 'MODULE_NOT_FOUND',
#26 0.520   requireStack: [ '/srv/build.js' ]
#26 0.520 }

```

**Comment by Kxiru** [comment]
@edlerd , After testing, I have realised that tests fail in demo/jenkins because the build scripts rely on all of the dependencies that you have asked me to move to DevDependencies (I ran them one by one to double check).
That being said, all of the version have been updated.

**Pull request merged**
